dist: xenial
sudo: required

language: go
go_import_path: github.com/src-d/engine
go:
  - 1.11.x

matrix:
  fast_finish: true

services:
  - docker

jobs:
  include:
    - name: 'Unit Tests'
      script:
        - make test-coverage
    - name: 'Generated code'
      script:
        - GO111MODULE=on go mod tidy
        - GO111MODULE=on go mod vendor
        - make no-changes-in-commit
        - make -C api proto
        - make no-changes-in-commit

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - DOCKER_PUSH_LATEST=1 make docker-push
